config/routes.rb
Rails.application.routes.draw do
  # User Users controller for Devise
  devise_for :users

  # Allow for user to sign out at path (destroy current session)
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  
  # Root to Home controller
  root to: "home#index"

  # Add RESTful routes to Providers, Patients, and Appointments
  resources :providers
  resources :patients
  resources :appointments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :provider
  belongs_to :patient

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :category, presence: true, inclusion: { in: %w(Routine Follow-up Urgent) }
  validates :description, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :provider
  has_many :appointments, dependent: :destroy # Delete all appointments belonging to a patient if they're removed from database

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true, numericality: { greater_than: 0 }
  validates :sex, presence: true, inclusion: { in: %w(Male Female) }
  validates :medical_notes, presence: true
end

app/models/provider.rb
class Provider < ApplicationRecord
    has_many :patients
    has_many :appointments

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :position, inclusion: { in: %w(Doctor Nurse Assistant) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Method to check if current user is an admin
  def admin?
    role == "Admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    before_action :authenticate_user! # Force user to sign in before viewing resources

    # Show all appointments
    def index
        @appointments = Appointment.all

        respond_to do |format|
            format.html
            format.json {
                render :json => @appointments
            }
        end
    end

    # Show appointment based on URL parameters
    def show
        @appointment = Appointment.find(params[:id])

        respond_to do |format|
            format.html
            format.json {
                render :json => @appointment
            }
        end
    end

    # Return form to create a new appointment
    def new
        @appointment = Appointment.new
    end

    # Create a new appointment from submission
    def create
        @appointment = Appointment.new(appointment_params)

        if @appointment.save
            redirect_to @appointment
            flash[:saved] = "Created a new appointment"
        else
            flash.now[:error] = "Something went wrong"
            render :new, status: :unprocessable_entity
        end
    end

    # Return form to edit an existing appointment
    def edit
        @appointment = Appointment.find(params[:id])
    end

    # Update appointment
    def update
        @appointment = Appointment.find(params[:id])

        if @appointment.update(appointment_params)
            redirect_to @appointment
            flash[:updated] = "Updated details for appointment"
        else
            flash.now[:error] = "Something went wrong"
            render :edit, status: :unprocessable_entity
        end
    end

    # Delete appointment
    def destroy
        @appointment = Appointment.find(params[:id])
        @appointment.destroy

        flash[:destroyed] = "Appointment removed"
        redirect_to root_path
    end

    private

    # Require stromg params, including foreign keys for Provider and Patient
    def appointment_params
        params.require(:appointment).permit(:start_date, :end_date, :category, :description, :provider_id, :patient_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    # Control what appears if user is signed in or not
    def index
        if user_signed_in?
            # Calculate metrics from database
            @provider_count = Provider.all.count
            @patient_count = Patient.all.count
            @appointment_count = Appointment.all.count

            respond_to do |format|
                format.html
            end
        else
            # Tell user to sign in if they are not
            render "splash"
        end
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    before_action :authenticate_user!

    def index
        @patients = Patient.all

        respond_to do |format|
            format.html
            format.json {
                render :json => @patients
            }
        end
    end

    def show
        @patient = Patient.find(params[:id])

        respond_to do |format|
            format.html
            format.json {
                render :json => @patient
            }
        end
    end

    def new
        @patient = Patient.new
    end

    def create
        @patient = Patient.new(patient_params)

        if @patient.save
            redirect_to @patient
            flash[:saved] = "Created a new patient"
        else
            flash.now[:error] = "Something went wrong"
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @patient = Patient.find(params[:id])
    end

    def update
        @patient = Patient.find(params[:id])

        if @patient.update(patient_params)
            redirect_to @patient
            flash[:updated] = "Updated details for patient"
        else
            flash.now[:error] = "Something went wrong"
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @patient = Patient.find(params[:id])
        @patient.destroy

        flash[:destroyed] = "Patient removed"
        redirect_to root_path
    end

    private

    def patient_params
        params.require(:patient).permit(:first_name, :last_name, :age, :sex, :medical_notes, :provider_id)
    end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
    # Only allow users with admin role to view and access these resources
    before_action :authenticate_user!

    def index
        unless current_user.admin?
            render "forbidden"
        end
        @providers = Provider.all

        respond_to do |format|
            format.html
            format.json {
                render :json => @providers
            }
        end
    end

    def show
        unless current_user.admin?
            render "forbidden"
        end
        @provider = Provider.find(params[:id])

        respond_to do |format|
            format.html
            format.json {
                render :json => @provider
            }
        end
    end

    def new
        unless current_user.admin?
            render "forbidden"
        end
        @provider = Provider.new
    end

    def create
        @provider = Provider.new(provider_params)

        if @provider.save
            redirect_to @provider
            flash[:saved] = "Created a new provider"
        else
            flash.now[:error] = "Something went wrong"
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        unless current_user.admin?
            render "forbidden"
        end
        @provider = Provider.find(params[:id])
    end

    def update
        @provider = Provider.find(params[:id])

        if @provider.update(provider_params)
            redirect_to @provider
            flash[:updated] = "Updated details for provider"
        else
            flash.now[:error] = "Something went wrong"
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @provider = Provider.find(params[:id])
        @provider.destroy

        flash[:destroyed] = "Provider removed"
        redirect_to root_path
    end

    private

    def provider_params
        params.require(:provider).permit(:first_name, :last_name, :position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/appointments/_form.html.erb
<%= form_with model: @appointment do |form| %>
    <%= form.label :start_date, "Start time: " %>
    <%= form.datetime_local_field :start_date %><br><br>

    <%= form.label :end_date, "End time: " %>
    <%= form.datetime_local_field :end_date %><br><br>

    Appointment type:
    <%= form.radio_button :category, "Routine" %>
    <%= form.label :category_routine, "Routine" %>
    <%= form.radio_button :category, "Follow-up" %>
    <%= form.label :category_followup, "Follow-up" %>
    <%= form.radio_button :category, "Urgent" %>
    <%= form.label :category_urgent, "Urgent" %><br><br>

    <%= form.label :description, "Description: " %>
    <%= form.text_area :description, size: "40x3" %><br><br>

    <%= form.label :provider_id, "Provider: " %>
    <%= form.number_field :provider_id %><br><br>

    <%= form.label :patient_id, "Patient: " %>
    <%= form.number_field :patient_id %><br><br>

    <%= submit_tag("Submit") %>
<% end %>

app/views/appointments/edit.html.erb
<h1>Edit details for <%= @appointment.patient.first_name %> <%= @appointment.patient.last_name %>'s appointment</h1>

<%= render "form" %>

<br>

<%= link_to "Delete appointment", appointment_path(@appointment), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?" } %>

<br>

<%= link_to "Return to appointment", appointment_path %>

<br>
<br>

<%= flash.now[:error] %>

app/views/appointments/index.html.erb
<%= flash[:destroyed] %>

<h3 style="text-align: center;">Manage appointments</h3>

<br>

<div style="display:flex; justify-content: center">
    <ol>
    <% @appointments.each { |appointment| %>
        <li>
            <%= link_to (appointment.patient.first_name + " " + appointment.patient.last_name + " on " + appointment.start_date.to_s), appointment %>
        </li>
    <% } %>
    </ol>
</div>

<p style="text-align: center;"><%= link_to "New appointment", new_appointment_path %></p>

app/views/appointments/new.html.erb
<h1>Create a new appointment</h1>

<%= render "form" %>

<br>

<%= link_to "Return home", root_path %>

<br>
<br>

<%= flash.now[:error] %>

app/views/appointments/show.html.erb
<%= flash[:saved] %>
<%= flash[:updated] %>
<h3 style="text-align: center;">View details for <%= @appointment.patient.first_name %> <%= @appointment.patient.last_name %>'s appointment</h3>

<p style="text-align: center;">Start date: <%= @appointment.start_date %></p>
<p style="text-align: center;">End date: <%= @appointment.end_date %></p>
<p style="text-align: center;">Category: <%= @appointment.category %></p>
<p style="text-align: center;">Description: <%= @appointment.description %></p>
<p style="text-align: center;">Associated provider: <%= @appointment.provider.position %> <%= @appointment.provider.first_name %> <%= @appointment.provider.last_name %></p>

<p style="text-align: center;"><%= link_to "Edit appointment", edit_appointment_path %><br></p>
<p style="text-align: center;"><%= link_to "Delete appointment", appointment_path(@appointment), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?" } %></p>

<p style="text-align: center;"><%= link_to "Return home", root_path %></p>

app/views/home/index.html.erb
<% if current_user.admin? %>

<br>
<br>
<div style="text-align: center; font-size: 24px;">Patient Zero Admin Dashboard</div>
<br>
<br>

<div style="display: flex; justify-content: center; gap: 50px;">

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Providers</h5>
    <p class="card-text">Number of providers:</p>
    <p><%= @provider_count %></p>
    <a href="http://localhost:3000/providers" class="btn btn-primary">View providers</a>
  </div>
</div>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Patients</h5>
    <p class="card-text">Number of patients:</p>
    <p><%= @patient_count %></p>
    <a href="http://localhost:3000/patients" class="btn btn-primary">View patients</a>
  </div>
</div>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Appointments</h5>
    <p class="card-text">Number of appointments:</p>
    <p><%= @appointment_count %></p>
    <a href="http://localhost:3000/appointments" class="btn btn-primary">View appointments</a>
  </div>
</div>

</div>

<br>
<br>
<br>
<br>

<% else %>

<br>
<br>
<div style="text-align: center; font-size: 24px;">Welcome to Patient Zero!</div>
<br>
<br>

<div style="display: flex; justify-content: center; gap: 50px;">

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Patients</h5>
    <a href="http://localhost:3000/patients" class="btn btn-primary">View and make patients</a>
  </div>
</div>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Appointments</h5>
    <a href="http://localhost:3000/appointments" class="btn btn-primary">View and make appointments</a>
  </div>
</div>

</div>

<br>
<br>
<br>
<br>

<% end %>

app/views/home/splash.html.erb
<br>
<br>
<br>
<br>

<div style="display: flex; justify-content: center">

<div class="card" style="width: 36rem; text-align: center;">
  <div class="card-body">
    <h5 class="card-title">Please sign in to continue to Patient Zero</h5>
    <a href="http://localhost:3000/users/sign_in" class="btn btn-primary">Sign in</a>
  </div>
</div>

</div>

<br>
<br>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patient Zero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg fixed-top" id="mainNav" style="background-color: #d6ead4;">
        <div class="container" style="background-color: #d6ead4;">
            <a class="navbar-brand">Patient Zero</a>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="http://localhost:3000/">Home</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="http://localhost:3000/patients">Patients</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="http://localhost:3000/appointments">Appointments</a></li>
                    <% if user_signed_in? %>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="http://localhost:3000/users/sign_out">Sign out</a></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>

    <br>
    <br>
    <br>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <br>
    <br>
    <br>

    <!-- Footer-->
    <footer class="footer text-center" style="background-color: #d6ead4;">
      <div>
        <br>
          Patient Zero is a healthcare website for medical providers to manage their patients.
        <br>
        <br>
      </div>
    </footer>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with model: @patient do |form| %>
    <%= form.label :first_name, "First name: " %>
    <%= form.text_field :first_name %><br><br>

    <%= form.label :last_name, "Last name: " %>
    <%= form.text_field :last_name %><br><br>

    <%= form.label :age, "Age: " %>
    <%= form.number_field :age, step: 1 %><br><br>

    Sex:
    <%= form.radio_button :sex, "Male" %>
    <%= form.label :sex_male, "Male" %>
    <%= form.radio_button :sex, "Female" %>
    <%= form.label :sex_female, "Female" %><br><br>

    <%= form.label :medical_notes, "Medical notes: " %>
    <%= form.text_area :medical_notes, size: "40x3" %><br><br>

    <%= form.label :provider_id, "Provider: " %>
    <%= form.number_field :provider_id %><br><br>

    <%= submit_tag("Submit") %>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit details for <%= @patient.first_name %> <%= @patient.last_name %></h1>

<%= render "form" %>

<br>

<%= link_to "Delete patient", patient_path(@patient), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?" } %>

<br>

<%= link_to "Return to patient", patient_path %>

<br>
<br>

<%= flash.now[:error] %>

app/views/patients/index.html.erb
<%= flash[:destroyed] %>

<h3 style="text-align: center;">Manage patients</h3>

<br>

<div style="display:flex; justify-content: center">
    <ol>
    <% @patients.each { |patient| %>
        <li>
            <%= link_to (patient.first_name + " " + patient.last_name), patient %>
        </li>
    <% } %>
    </ol>
</div>

<p style="text-align: center;"><%= link_to "New patient", new_patient_path %></p>

app/views/patients/new.html.erb
<h1>Create a new patient</h1>

<%= render "form" %>

<br>

<%= link_to "Return home", root_path %>

<br>
<br>

<%= flash.now[:error] %>

app/views/patients/show.html.erb
<%= flash[:saved] %>
<%= flash[:updated] %>
<h3 style="text-align: center;">View details for <%= @patient.first_name %> <%= @patient.last_name %></h3>

<p style="text-align: center;">Name: <%= @patient.first_name %> <%= @patient.last_name %></p>
<p style="text-align: center;">Age: <%= @patient.age %></p>
<p style="text-align: center;">Sex: <%= @patient.sex %></p>
<p style="text-align: center;">Medical notes: <%= @patient.medical_notes %></p>
<p style="text-align: center;">Associated provider: <%= @patient.provider.position %> <%= @patient.provider.first_name %> <%= @patient.provider.last_name %></p>

<p style="text-align: center;"><%= link_to "Edit patient", edit_patient_path %><br></p>
<p style="text-align: center;"><%= link_to "Delete patient", provider_path(@patient), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?" } %></p>

<p style="text-align: center;"><%= link_to "Return home", root_path %></p>

app/views/providers/_form.html.erb
<%= form_with model: @provider do |form| %>
    <%= form.label :first_name, "First name: " %>
    <%= form.text_field :first_name %><br><br>

    <%= form.label :last_name, "Last name: " %>
    <%= form.text_field :last_name %><br><br>

    Provider role:
    <%= form.radio_button :position, "Doctor" %>
    <%= form.label :position_doctor, "Doctor" %>
    <%= form.radio_button :position, "Nurse" %>
    <%= form.label :position_nurse, "Nurse" %>
    <%= form.radio_button :position, "Assistant" %>
    <%= form.label :position_assistant, "Assistant" %><br><br>

    <%= submit_tag("Submit") %>
<% end %>

app/views/providers/edit.html.erb
<h1>Edit details for <%= @provider.position %> <%= @provider.last_name %></h1>

<%= render "form" %>

<br>

<%= link_to "Delete provider", provider_path(@provider), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?" } %>

<br>

<%= link_to "Return to provider", provider_path %>

<br>
<br>

<%= flash.now[:error] %>

app/views/providers/forbidden.html.erb
<div style="display: flex; justify-content: center">
    <div>
        You are forbidden from viewing this page.
        <br>
        <%= link_to "Return home", root_path %>
    </div>
</div>

app/views/providers/index.html.erb
<%= flash[:destroyed] %>

<h3 style="text-align: center;">Manage providers</h3>

<br>

<div style="display:flex; justify-content: center">
    <ol>
    <% @providers.each { |provider| %>
        <li>
            <%= link_to (provider.first_name + " " + provider.last_name), provider %>
        </li>
    <% } %>
    </ol>
</div>

<p style="text-align: center;"><%= link_to "New provider", new_provider_path %></p>

app/views/providers/new.html.erb
<h1>Create a new provider</h1>

<%= render "form" %>

<br>

<%= link_to "Return home", root_path %>

<br><br>

<%= flash.now[:error] %>

app/views/providers/show.html.erb
<%= flash[:saved] %>
<%= flash[:updated] %>

<h3 style="text-align: center;">View details for <%= @provider.position %> <%= @provider.last_name %></h3>

<p style="text-align: center;">Name: <%= @provider.first_name %> <%= @provider.last_name %></p>
<p style="text-align: center;">Role: <%= @provider.position %></p>

<p style="text-align: center;"><%= link_to "Edit provider", edit_provider_path %><br></p>
<p style="text-align: center;"><%= link_to "Delete provider", provider_path(@provider), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?" } %></p>

<p style="text-align: center;"><%= link_to "Return home", root_path %></p>